export const GET_USER_WALLET_REQUEST ="GET_USER_WALLET_REQUEST";
export const GET_USER_WALLET_SUCCESS ="GET_USER_WALLET_SUCCESS";
export const GET_USER_WALLET_FAILURE ="GET_USER_WALLET_FAILURE";

export const GET_WALLET_TRANSACTION_REQUEST ="GET_WALLET_TRANSACTION_REQUEST";
export const GET_WALLET_TRANSACTION_SUCCESS ="GET_WALLET_TRANSACTION_SUCCESS";
export const GET_WALLET_TRANSACTION_FAILURE ="GET_WALLET_TRANSACTION_FAILURE";

export const DEPOSITE_MONEY_REQUEST ="DEPOSITE_MONEY_REQUEST";
export const DEPOSITE_MONEY_SUCCESS ="DEPOSITE_MONEY_SUCCESS";
export const DEPOSITE_MONEY_FAILURE ="DEPOSITE_MONEY_FAILURE";

export const TRANSFER_MONEY_REQUEST ="TRANSFER_MONEY_REQUEST";
export const TRANSFER_MONEY_SUCCESS ="TRANSFER_MONEY_SUCCESS";
export const TRANSFER_MONEY_FAILURE ="TRANSFER_MONEY_FAILURE";